# -*- coding: utf-8 -*-
"""
This is part of WebScout software
Docs EN: http://hack4sec.pro/wiki/index.php/WebScout_en
Docs RU: http://hack4sec.pro/wiki/index.php/WebScout
License: MIT
Copyright (c) Anton Kuzmin <http://anton-kuzmin.ru> (ru) <http://anton-kuzmin.pro> (en)

ContentDiscovery module class
"""
import os
import random
import subprocess
import datetime
from urlparse import urlparse

from classes.kernel.WSException import WSException
from classes.modules.UrlsDict import UrlsDict
from classes.modules.UrlsModules import UrlsModules
from classes.modules.params.ContentDiscoveryModuleParams import ContentDiscoveryModuleParams
from classes.kernel.WSModule import WSModule
from classes.Registry import Registry
from classes.kernel.WSOption import WSOption
from classes.generators.DictOfMask import DictOfMask
from classes.generators.ContentDiscoveryNameGenerator import ContentDiscoveryNameGenerator


class ContentDiscovery(UrlsDict):
    """ ContentDiscovery module class """
    logger_name = 'content_discovery'
    exts = []

    def __init__(self, kernel):
        UrlsModules.__init__(self, kernel)
        self.options = ContentDiscoveryModuleParams().get_options()
        self.exts = self.options['discovery-exts'].value.split(",")

    def validate_main(self):
        """ Check users params """
        super(ContentDiscovery, self).validate_main()

        if len(self.options['urls-file'].value) and not os.path.exists(self.options['urls-file'].value):
            raise WSException(
                "File with urls '{0}' not exists!".format(self.options['urls-file'].value)
            )

    def write_bases_variants(self, base_fh):
        """
        Write in file basese variants for search.
        Using for write one big dictionary.
        :param base_fh:
        :return:
        """
        fh = open(Registry().get('wr_path') + "/bases/content-discovery/base.txt")
        while True:
            line = fh.readline()
            if not line:
                break
            line = line.strip()

            gens = ContentDiscoveryNameGenerator.gen_exts_variants(line, self.exts)
            for gen in gens:
                base_fh.write(gen + "\n")

        fh.close()

    def write_tools_variants(self, base_fh):
        """
        Write in file variants from tools dict.
        Using for write one big dictionary.
        :param base_fh:
        :return:
        """
        fh = open(Registry().get('wr_path') + "/bases/content-discovery/tools-and-others.txt")
        while True:
            line = fh.readline()
            if not line:
                break
            line = line.strip()

            base_fh.write(line + "\n")

        fh.close()

    def write_urls_file_variants(self, urls_file, base_fh):
        """
        Write in file mutation variants of already known urls
        :param urls_file:
        :param base_fh:
        :return:
        """
        urls_fh = open(urls_file)
        while True:
            line = urls_fh.readline()
            if not line:
                break
            line = line.strip()

            parsed_url = urlparse(line)
            if not len(parsed_url.path) or parsed_url.path == '/':
                continue

            path = parsed_url.path[1:]  # Cut start /
            if path[-1] == "/":  # Cut end /
                path = path[:-1]

            c = 0
            parts = path.split("/")
            for part in parts:
                gens = []
                c += 1

                gens.extend(ContentDiscoveryNameGenerator.gen_backups_variants(part, c == len(parts)))
                gens.extend(ContentDiscoveryNameGenerator.gen_letters_variants(part, c == len(parts)))
                if c == len(parts): # It`s may be file
                    gens.extend(ContentDiscoveryNameGenerator.gen_numbers_variants(part, True))
                gens.extend(ContentDiscoveryNameGenerator.gen_numbers_variants(part, False))

                if c == len(parts):  # It`s may be file
                    baseword = part[:part.rfind(".")] if part.count(".") else part
                else:
                    baseword = part

                gens.extend(ContentDiscoveryNameGenerator.gen_exts_variants(baseword, self.exts))
                for gen in gens:
                    base_fh.write(gen + "\n")

        urls_fh.close()

    def write_mask_variants(self, mask, base_fh):
        """
        Write in file variants names generated by mask
        :param mask:
        :param base_fh:
        :return:
        """
        dom = DictOfMask(mask, 0, 0)
        while True:
            line = dom.get()
            if line is None:
                break

            gens = ContentDiscoveryNameGenerator.gen_exts_variants(line, self.exts)
            for gen in gens:
                base_fh.write(gen + "\n")
        del dom

    def write_years(self, base_fh):
        """
        Write in file years variants, from 2010 to current
        :param base_fh:
        :return:
        """
        now = datetime.datetime.now()
        for year in range(2010, now.year+1):
            base_fh.write(str(year) + "\n")

    def build_attack_list(self, dict_path):
        """
        Building big monolit dict for attack
        :param dict_path:
        :return:
        """
        base_fh = open(dict_path, 'w')

        self.write_years(base_fh)
        self.write_bases_variants(base_fh)
        self.write_tools_variants(base_fh)
        self.write_mask_variants('?l?d,1,2', base_fh)

        if len(self.options['urls-file'].value):  # TODO is it checking for exists?
            self.write_urls_file_variants(self.options['urls-file'].value, base_fh)

        base_fh.close()

    def do_work(self):
        """ Start working """
        self.validate_main()

        dict_path = "/tmp/web-scout-content-discovery-%d.txt" % random.randint(1000000, 9000000)

        self.build_attack_list(dict_path)

        dict_path_uniq = dict_path + "-uniq"
        subprocess.check_output("sort -u {0} > {1}".format(dict_path, dict_path_uniq), shell=True)

        tmp_files = Registry().get('tmp_files')
        tmp_files.append(dict_path)
        tmp_files.append(dict_path_uniq)
        Registry().set('tmp_files', tmp_files)

        self.options['dict'] = WSOption(
            "dict",
            "Dictionary for work",
            "",
            True,
            ['--dict']
        )
        self.options['dict'].value = dict_path_uniq

        WSModule.do_work(self)
